#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import numpy as np
import csv
import matplotlib.pyplot as plt

filenames = ['red.csv', 'green.csv', 'blue.csv']
data = []

for filename in filenames:
    with open(filename, mode='r') as file:
        csv_reader = csv.reader(file)
        file_data = []
        for row in csv_reader:
            row_data = []
            # The following for loop was generated by ChatGPT to handle blank/mismatched cells. The erroneous code was provided and the prompt "when I run the code it says "invalid literal for int() with base 10"
            for value in row:
                value = value.strip()
                if value:
                    try:
                        row_data.append(int(value))
                    except ValueError:
                        print(f"Warning: '{value}' could not be converted to an integer.")
                        row_data.append(0)
                else:
                    row_data.append(0)
            file_data.append(row_data)
        data.append(np.array(file_data))
#the following -1 axis stack was generated by ChatGPT.  I provided the code and the following prompt "I am trying to stack each position, i.e. row 1 column 1 in the blue.csv with row 1 column 1 in the red.csv with np.stack. these are pixel values."
stacked_data = np.stack(data, axis=-1)

plt.imshow(stacked_data)
plt.show()
